language: cpp

notifications:
  email:
    recipients:
      - rainer.kuemmerle@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

# where do we want to build
matrix:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      dist: focal
    - os: linux
      arch: amd64
      compiler: clang
      dist: focal
    - os: osx
      arch: amd64
      osx_image: xcode12.2

before_install:
  - env | sort

# install:
#   - script/install-deps-${TRAVIS_OS_NAME}.sh

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DBUILD_UNITTESTS=ON ..
  - cat g2o/config.h

script:
  - make -j $(nproc)
  - ctest --extra-verbose

# installing dependencies
addons:
  apt: # linux
    packages:
      - libeigen3-dev
      - qtdeclarative5-dev
      - qt5-qmake
      - libqglviewer-dev-qt5
      - libsuitesparse-dev
  homebrew: # mac os
    packages:
      - cmake
      - eigen
